### ISSUE TITLE
create scroll to top button

### ISSUE THREAD

**Issue by VilloKodeHode** [VilloKodeHode/mega-collab-modul-s#45]
use branch 45-create-scroll-to-top-button for this issue

files:
/components/atom/ScrollToTopButton.jsx (needs to be created in this issue)
/app/layout.jsx: The component should be put here so it is visable at all pages.

create scroll to top button

- should not be visable when the user is at the top of the page
- should be easy to spot no matter what the background color is.

**Comment by KaterinaB10** [comment]
After pushing dev branch to branch 45-create-scroll-to-top-button, the button stopped work.

**Comment by KaterinaB10** [comment]
done
