### ISSUE TITLE
Light/Dark mode

### ISSUE THREAD

**Issue by Sebahoppkodehode** [VilloKodeHode/mega-collab-modul-s#46]
Make a switch button that can change the page from light mode to dark mode, and vise versa.

The switch should be placed in the nav/hamburger menu (hamburger might still be raw so be patient in that case).

The effect should persist through switching between pages.

This requires all styles to have a dark: tag in front of it. It is also needed to change the tailwind.config.js file to say what colors will be shown instead when it is darkmode.

This is more a styling issue then a javascript issue.

**Comment by kristofferfh** [comment]
I hate to admit defeat, but for now I've added [next-themes](https://github.com/pacocoursey/next-themes). I'll open up another issue and create my own implementation.
