### ISSUE TITLE
create designsystem

### ISSUE THREAD

**Issue by VilloKodeHode** [VilloKodeHode/mega-collab-modul-s#47]
must have:

colors:
  - 1-3 main colors (primary, secondary, tertiary)
  - shades of white, black (maybe grey?)

component styles:

**Comment by AndreK-B06** [comment]
Figma:
https://www.figma.com/team_invite/redeem/pEeYaFrpcJJ2Rw8eLWVBKR

**Comment by AndreK-B06** [comment]
Addend fonts in design system and mad variants with boldes and reguler.
Link to the google font are incuded her so its easyer to find and implement:

https://fonts.google.com/specimen/Oxygen?query=Oxygen

https://fonts.google.com/specimen/Poppins?query=Poppins

https://fonts.google.com/specimen/BioRhyme?query=BioRhyme

https://fonts.google.com/specimen/Inknut+Antiqua?query=Inknut+Antiqua

**Comment by AndreasB09** [comment]
Did some color suggestions. Light and Dark reverse. Picked out the Main/Secondary/Teritary colors but they could go in either order. Added some contrast colors for diversity. 

Threw together some color blocks to see if it fits.

Played around with some button suggestions. Lots of options.
