### ISSUE TITLE
fix tailwind config colors

### ISSUE THREAD

**Issue by VilloKodeHode** [VilloKodeHode/mega-collab-modul-s#54]
use branch 54-fix-tailwind-config-colors

Fix the colors in theme->extend->colors so it fits with the design system

**Comment by kristofferfh** [comment]
Adding colors to tailwind config based on Figma file by @AndreK-B06 @AndreasB09 

 https://www.figma.com/design/CDxFU5WZQ3pkWZFBpDl5lm/Design-System?node-id=0-1&t=80Tl6nrP0jArg7p2-0

**Comment by kristofferfh** [comment]
Resolved in #67
